% defines the lowerbound, the counter, and the highbound of the for loop respectively
i_values = -100:1:100;
% our function to be plotted, salted, and smoothed
y_values = 2 .* (i_values - 3).^2 + 4;
%adds the salted value generated by rand between -10000 to 10000
salted_values = (rand(size(y_values)) * 20000) - 10000;
y_values_salted = y_values + salted_values;
%grabs the 3 values around each y value and takes the average for said value
window_size = 3;
y_values_smoothed = movmean(y_values_salted, window_size)

plot(i_values, y_values, 'b-', 'LineWidth', 2);
hold on;

plot(i_values, y_values_salted, 'r.', 'MarkerSize', 8);

plot(i_values, y_values_smoothed, 'g-', 'LineWidth', 2); % Green line for smoothed data
hold off;

xlabel('x');
ylabel('y');
title('Plotter');
grid on;




